# Generated by Django 5.2 on 2025-04-05 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('aisle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('aisle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('eval_set', models.CharField(max_length=20)),
                ('order_number', models.IntegerField()),
                ('order_dow', models.IntegerField()),
                ('order_hour_of_day', models.IntegerField()),
                ('days_since_prior_order', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('aisle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instacart.aisle')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instacart.department')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_to_cart_order', models.IntegerField()),
                ('reordered', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instacart.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instacart.product')),
            ],
        ),
    ]
